import type { ProductType } from "./Types";
export const ProductData: ProductType[] = [
  {
    id: 1,
    name: "Nike Air Force 1",
    price: 150,
    discountPrice: 120,
    discountPercent: 20,
    ratingValue: 4.5,
    ratingCount: 120,
    isHot: true,
    colors: ["white", "black", "red"],
    category: "Sneakers",
    imageUrl:
      "https://images.unsplash.com/photo-1656164847621-4665c4c397da?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8TmlrZSUyMEFpciUyMEZvcmNlJTIwMXxlbnwwfHwwfHx8MA%3D%3D",
  },
  {
    id: 2,
    name: "Leather Belt",
    price: 50,
    ratingValue: 4.2,
    ratingCount: 80,
    isHot: false,
    colors: ["brown", "black"],
    category: "Belt",
    imageUrl:
      "https://images.unsplash.com/photo-1664286074176-5206ee5dc878?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8TGVhdGhlciUyMEJlbHR8ZW58MHx8MHx8fDA%3D",
  },
  {
    id: 3,
    name: "Canvas Backpack",
    price: 80,
    discountPrice: 60,
    discountPercent: 25,
    ratingValue: 4.8,
    ratingCount: 200,
    isHot: true,
    colors: ["blue", "gray", "black"],
    category: "Bag",
    imageUrl:
      "https://images.unsplash.com/photo-1547949003-9792a18a2601?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8Y2FudmFzJTIwYmFja3BhY2t8ZW58MHx8MHx8fDA%3D",
  },
  {
    id: 4,
    name: "Adidas Stan Smith",
    price: 130,
    ratingValue: 4.6,
    ratingCount: 150,
    isHot: false,
    colors: ["white", "green"],
    category: "Sneakers",
    imageUrl:
      "https://assets.adidas.com/images/w_600,f_auto,q_auto/701aeaab5d4f4ed382da2cb14562d9af_9366/Stan_Smith_Shoes_White_ID0268_01_standard.jpg",
  },
  // ... adding more products to reach 24
  {
    id: 5,
    name: "Classic Watch",
    price: 250,
    ratingValue: 4.9,
    ratingCount: 300,
    isHot: true,
    colors: ["silver", "gold"],
    category: "Watch",
    imageUrl:
      "https://images.unsplash.com/photo-1669621952687-8ba483e11a9b?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Y2xhc3NpYyUyMHdhdGNofGVufDB8fDB8fHww",
  },
  {
    id: 6,
    name: "Tote Bag",
    price: 65,
    ratingValue: 4.3,
    ratingCount: 95,
    isHot: false,
    colors: ["beige", "black"],
    category: "Bag",
    imageUrl:
      "https://images.unsplash.com/photo-1574365569389-a10d488ca3fb?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8dG90ZSUyMGJhZ3xlbnwwfHwwfHx8MA%3D%3D",
  },
  {
    id: 7,
    name: "Puma Suede Classic",
    price: 110,
    ratingValue: 4.4,
    ratingCount: 110,
    isHot: false,
    colors: ["black", "red", "blue"],
    category: "Sneakers",
    imageUrl: "https://m.media-amazon.com/images/I/71HjpwKecFL._SL1500_.jpg",
  },
  {
    id: 8,
    name: "Woven Belt",
    price: 45,
    ratingValue: 4.1,
    ratingCount: 70,
    isHot: false,
    colors: ["tan", "navy"],
    category: "Belt",
    imageUrl:
      "https://www.asiansports.in/cdn/shop/files/Untitled_design_9.png?v=1742205372&width=1080",
  },
  {
    id: 9,
    name: "Digital Sports Watch",
    price: 90,
    discountPrice: 75,
    discountPercent: 17,
    ratingValue: 4.7,
    ratingCount: 180,
    isHot: true,
    colors: ["black", "orange"],
    category: "Watch",
    imageUrl:
      "https://images.unsplash.com/photo-1617625802912-cde586faf331?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fERpZ2l0YWwlMjBTcG9ydHMlMjBXYXRjaHxlbnwwfHwwfHx8MA%3D%3D",
  },
  {
    id: 10,
    name: "Messenger Bag",
    price: 100,
    ratingValue: 4.6,
    ratingCount: 130,
    isHot: false,
    colors: ["green", "black"],
    category: "Bag",
    imageUrl: "https://m.media-amazon.com/images/I/71jd7iWjhEL._UY1000_.jpg",
  },
  {
    id: 11,
    name: "Vans Old Skool",
    price: 95,
    ratingValue: 4.7,
    ratingCount: 250,
    isHot: true,
    colors: ["black", "white"],
    category: "Sneakers",
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2ATJwy-lnf5gnf6H7HFD4B1zXwZFFAeDVjQ&s",
  },
  {
    id: 12,
    name: "Reversible Belt",
    price: 55,
    ratingValue: 4.3,
    ratingCount: 85,
    isHot: false,
    colors: ["black", "brown"],
    category: "Belt",
    imageUrl:
      "https://hidesign.com/cdn/shop/files/8903439837853__1_1024x1024.jpg?v=1702908469",
  },
  {
    id: 13,
    name: "Converse Chuck 70",
    price: 125,
    ratingValue: 4.8,
    ratingCount: 280,
    isHot: false,
    colors: ["cream", "black", "sunflower"],
    category: "Sneakers",
    imageUrl:
      "https://www.converse.in/media/catalog/product/a/0/a00916c_a_107x1.jpg",
  },
  {
    id: 14,
    name: "Minimalist Watch",
    price: 180,
    ratingValue: 4.9,
    ratingCount: 220,
    isHot: false,
    colors: ["white", "black", "rose-gold"],
    category: "Watch",
    imageUrl:
      "https://watchessy.com/wp-content/uploads/2020/06/custom-watches.jpg",
  },
  {
    id: 15,
    name: "Duffle Bag",
    price: 115,
    discountPrice: 90,
    discountPercent: 22,
    ratingValue: 4.5,
    ratingCount: 140,
    isHot: true,
    colors: ["navy", "gray"],
    category: "Bag",
    imageUrl:
      "https://plus.unsplash.com/premium_photo-1671028547420-a541b5a1243e?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZHVmZmxlJTIwYmFnfGVufDB8fDB8fHww",
  },
  {
    id: 16,
    name: "New Balance 574",
    price: 140,
    ratingValue: 4.6,
    ratingCount: 190,
    isHot: false,
    colors: ["gray", "navy", "burgundy"],
    category: "Sneakers",
    imageUrl: "https://m.media-amazon.com/images/I/71af56zbNgL._UY1000_.jpg",
  },
  {
    id: 17,
    name: "Studded Belt",
    price: 60,
    ratingValue: 4.0,
    ratingCount: 65,
    isHot: false,
    colors: ["black", "silver"],
    category: "Belt",
    imageUrl:
      "https://images-cdn.ubuy.co.in/654bf18ac32206043a1e2293-studded-belts-punk-rock-belts-for-women.jpg",
  },
  {
    id: 18,
    name: "Chronograph Watch",
    price: 350,
    discountPrice: 300,
    discountPercent: 14,
    ratingValue: 4.9,
    ratingCount: 400,
    isHot: true,
    colors: ["blue", "steel", "black"],
    category: "Watch",
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhCIwM_S_fGGcQs9TamrpXXFeTKoNMPjeK5g&s",
  },
  {
    id: 19,
    name: "Laptop Bag",
    price: 95,
    ratingValue: 4.7,
    ratingCount: 160,
    isHot: false,
    colors: ["black", "charcoal"],
    category: "Bag",
    imageUrl:
      "https://carrypro.in/cdn/shop/files/5_f0fe29e3-7769-4322-bcc0-3fa5dfe39ee7.jpg?v=1725980734&width=1080",
  },
  {
    id: 20,
    name: "Reebok Classic",
    price: 105,
    ratingValue: 4.3,
    ratingCount: 100,
    isHot: false,
    colors: ["white", "gum"],
    category: "Sneakers",
    imageUrl:
      "https://images-cdn.ubuy.co.in/67e2481ef02d7324ef309bd6-reebok-womens-princess-sneakers-white.jpg",
  },
  {
    id: 21,
    name: "Sling Bag",
    price: 55,
    ratingValue: 4.4,
    ratingCount: 90,
    isHot: true,
    colors: ["black", "red"],
    category: "Bag",
    imageUrl:
      "https://images.unsplash.com/photo-1645276281394-395ff9f072a7?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8U2xpbmclMjBCYWd8ZW58MHx8MHx8fDA%3D",
  },
  {
    id: 22,
    name: "Automatic Watch",
    price: 500,
    ratingValue: 5.0,
    ratingCount: 550,
    isHot: false,
    colors: ["black", "leather-brown"],
    category: "Watch",
    imageUrl:
      "https://images.unsplash.com/photo-1748327929572-2ccf5716d3b9?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8YXV0b21hdGljJTIwd2F0Y2h8ZW58MHx8MHx8fDA%3D",
  },
  {
    id: 23,
    name: "Canvas Belt",
    price: 35,
    ratingValue: 3.9,
    ratingCount: 50,
    isHot: false,
    colors: ["khaki", "olive"],
    category: "Belt",
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhBm5-O_swnPUtcElkU1EfFk9rjr70JB3OHA&s",
  },
  {
    id: 24,
    name: "ASICS Gel-Lyte III",
    price: 160,
    discountPrice: 130,
    discountPercent: 19,
    ratingValue: 4.8,
    ratingCount: 210,
    isHot: true,
    colors: ["teal", "gray", "orange"],
    category: "Sneakers",
    imageUrl:
      "https://www.asics.co.in/media/catalog/product/1/2/1203a330_022_sr_rt_glb-base.jpg",
  },
];
