import type { ProductType } from "./Types";

export const ProductData: ProductType[] = [
  {
    id: 1,
    name: 'Nike Air Force 1',
    price: 150,
    discountPrice: 120,
    discountPercent: 20,
    ratingValue: 4.5,
    ratingCount: 120,
    isHot: true,
    colors: ['white', 'black', 'red'],
    category: 'Sneakers',
    imageUrl: 'https://via.placeholder.com/300',
  },
  {
    id: 2,
    name: 'Leather Belt',
    price: 50,
    ratingValue: 4.2,
    ratingCount: 80,
    isHot: false,
    colors: ['brown', 'black'],
    category: 'Belt',
    imageUrl: 'https://via.placeholder.com/300',
  },
  {
    id: 3,
    name: 'Canvas Backpack',
    price: 80,
    discountPrice: 60,
    discountPercent: 25,
    ratingValue: 4.8,
    ratingCount: 200,
    isHot: true,
    colors: ['blue', 'gray', 'black'],
    category: 'Bag',
    imageUrl: 'https://via.placeholder.com/300',
  },
  {
    id: 4,
    name: 'Adidas Stan Smith',
    price: 130,
    ratingValue: 4.6,
    ratingCount: 150,
    isHot: false,
    colors: ['white', 'green'],
    category: 'Sneakers',
    imageUrl: 'https://via.placeholder.com/300',
  },
  // ... adding more products to reach 24
  {
    id: 5,
    name: 'Classic Watch',
    price: 250,
    ratingValue: 4.9,
    ratingCount: 300,
    isHot: true,
    colors: ['silver', 'gold'],
    category: 'Watch',
    imageUrl: 'https://via.placeholder.com/300',
  },
  {
    id: 6,
    name: 'Tote Bag',
    price: 65,
    ratingValue: 4.3,
    ratingCount: 95,
    isHot: false,
    colors: ['beige', 'black'],
    category: 'Bag',
    imageUrl: 'https://via.placeholder.com/300',
  },
  {
    id: 7,
    name: 'Puma Suede Classic',
    price: 110,
    ratingValue: 4.4,
    ratingCount: 110,
    isHot: false,
    colors: ['black', 'red', 'blue'],
    category: 'Sneakers',
    imageUrl: 'https://via.placeholder.com/300',
  },
  {
    id: 8,
    name: 'Woven Belt',
    price: 45,
    ratingValue: 4.1,
    ratingCount: 70,
    isHot: false,
    colors: ['tan', 'navy'],
    category: 'Belt',
    imageUrl: 'https://via.placeholder.com/300',
  },
  {
    id: 9,
    name: 'Digital Sports Watch',
    price: 90,
    discountPrice: 75,
    discountPercent: 17,
    ratingValue: 4.7,
    ratingCount: 180,
    isHot: true,
    colors: ['black', 'orange'],
    category: 'Watch',
    imageUrl: 'https://via.placeholder.com/300',
  },
  {
    id: 10,
    name: 'Messenger Bag',
    price: 100,
    ratingValue: 4.6,
    ratingCount: 130,
    isHot: false,
    colors: ['green', 'black'],
    category: 'Bag',
    imageUrl: 'https://via.placeholder.com/300',
  },
  {
    id: 11,
    name: 'Vans Old Skool',
    price: 95,
    ratingValue: 4.7,
    ratingCount: 250,
    isHot: true,
    colors: ['black', 'white'],
    category: 'Sneakers',
    imageUrl: 'https://via.placeholder.com/300',
  },
  {
    id: 12,
    name: 'Reversible Belt',
    price: 55,
    ratingValue: 4.3,
    ratingCount: 85,
    isHot: false,
    colors: ['black', 'brown'],
    category: 'Belt',
    imageUrl: 'https://via.placeholder.com/300',
  },
  {
    id: 13,
    name: 'Converse Chuck 70',
    price: 125,
    ratingValue: 4.8,
    ratingCount: 280,
    isHot: false,
    colors: ['cream', 'black', 'sunflower'],
    category: 'Sneakers',
    imageUrl: 'https://via.placeholder.com/300',
  },
  {
    id: 14,
    name: 'Minimalist Watch',
    price: 180,
    ratingValue: 4.9,
    ratingCount: 220,
    isHot: false,
    colors: ['white', 'black', 'rose-gold'],
    category: 'Watch',
    imageUrl: 'https://via.placeholder.com/300',
  },
  {
    id: 15,
    name: 'Duffle Bag',
    price: 115,
    discountPrice: 90,
    discountPercent: 22,
    ratingValue: 4.5,
    ratingCount: 140,
    isHot: true,
    colors: ['navy', 'gray'],
    category: 'Bag',
    imageUrl: 'https://via.placeholder.com/300',
  },
  {
    id: 16,
    name: 'New Balance 574',
    price: 140,
    ratingValue: 4.6,
    ratingCount: 190,
    isHot: false,
    colors: ['gray', 'navy', 'burgundy'],
    category: 'Sneakers',
    imageUrl: 'https://via.placeholder.com/300',
  },
  {
    id: 17,
    name: 'Studded Belt',
    price: 60,
    ratingValue: 4.0,
    ratingCount: 65,
    isHot: false,
    colors: ['black', 'silver'],
    category: 'Belt',
    imageUrl: 'https://via.placeholder.com/300',
  },
  {
    id: 18,
    name: 'Chronograph Watch',
    price: 350,
    discountPrice: 300,
    discountPercent: 14,
    ratingValue: 4.9,
    ratingCount: 400,
    isHot: true,
    colors: ['blue', 'steel', 'black'],
    category: 'Watch',
    imageUrl: 'https://via.placeholder.com/300',
  },
  {
    id: 19,
    name: 'Laptop Bag',
    price: 95,
    ratingValue: 4.7,
    ratingCount: 160,
    isHot: false,
    colors: ['black', 'charcoal'],
    category: 'Bag',
    imageUrl: 'https://via.placeholder.com/300',
  },
  {
    id: 20,
    name: 'Reebok Classic',
    price: 105,
    ratingValue: 4.3,
    ratingCount: 100,
    isHot: false,
    colors: ['white', 'gum'],
    category: 'Sneakers',
    imageUrl: 'https://via.placeholder.com/300',
  },
  {
    id: 21,
    name: 'Sling Bag',
    price: 55,
    ratingValue: 4.4,
    ratingCount: 90,
    isHot: true,
    colors: ['black', 'red'],
    category: 'Bag',
    imageUrl: 'https://via.placeholder.com/300',
  },
  {
    id: 22,
    name: 'Automatic Watch',
    price: 500,
    ratingValue: 5.0,
    ratingCount: 550,
    isHot: false,
    colors: ['black', 'leather-brown'],
    category: 'Watch',
    imageUrl: 'https://via.placeholder.com/300',
  },
  {
    id: 23,
    name: 'Canvas Belt',
    price: 35,
    ratingValue: 3.9,
    ratingCount: 50,
    isHot: false,
    colors: ['khaki', 'olive'],
    category: 'Belt',
    imageUrl: 'https://via.placeholder.com/300',
  },
  {
    id: 24,
    name: 'ASICS Gel-Lyte III',
    price: 160,
    discountPrice: 130,
    discountPercent: 19,
    ratingValue: 4.8,
    ratingCount: 210,
    isHot: true,
    colors: ['teal', 'gray', 'orange'],
    category: 'Sneakers',
    imageUrl: 'https://via.placeholder.com/300',
  },
];